### ISSUE TITLE
Error when trying to use the software, nbt related

### ISSUE THREAD

**Issue by NeoZeromus** [mlaidma/bg-sedit#2]
got this message when trying to use the software:

Traceback (most recent call last):
  File "c:\Users\Alex\Desktop\bg-sedit-release-v1.0.0\sedit.py", line 146, in <module>
    repack(args.schematic, args.output, args.map)
  File "c:\Users\Alex\Desktop\bg-sedit-release-v1.0.0\sedit.py", line 92, in repack
    for tag in nbtfile["data"]:
  File "C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nbtlib\tag.py", line 1167, in __getitem__
    return super().__getitem__(key)
KeyError: 'data'

https://pastebin.com/raw/jDuj7wTX this is the schematic
https://pastebin.com/WmbXRb54 this one is the map

**Comment by NeoZeromus** [comment]
I was using a past version of the nbt lib my b
