### ISSUE TITLE
Invalid pasted JSON error from template manager

### ISSUE THREAD

**Issue by ProbNotTrunks** [mlaidma/bg-sedit#3]
Not sure if this is related to the recent re-writing of the building gadgets mod, as it is now building gadgets 2, but I was able to swap all the blocks an the new edited JSON was created. But when I tried to paste the code in the template manager in the game, it says "Invalid pasted JSON". Currently playing the Direwolf20 1.20 pack using this [design](https://gist.github.com/moomoo84/1aba30021a51cc9ec683dbc8e5baf437) from GitHub user moomoo84, A.K.A. Howester84. Though, now slightly modified thanks to your tool, which worked wonders.

**Comment by mlaidma** [comment]
Thanks for reaching out! Just to understand your message better - did it work or did you just get "Invalid pasted JSON"? 

If you encountered any issues with "Invalid pasted JSON" as you mentioned, can you provide steps to reproduce? I am not actively developing this, but I might take a look at it, if it is not working anymore with new versions of BG.

**Comment by ProbNotTrunks** [comment]
Thanks for getting back! Yeah, there was a massive rewrite of the code for BG, it's now BG2. I was able to follow all steps listed for your tool and get the edited JSON file spit back out. All I did was copy and paste the entirety of the code from the JSON into the template manager and when I hit "paste" within the template manager GUI, it spit out the text "Invalid pasted JSON". I am curious of this is something to do with how the mapping is formatted in the body of the code? I am away from my computer now, but will try to recreate my steps and add them here when I have a moment. Thank you for your help and for making a great tool. Wish this was somehow integrated within the mod itself.

**Comment by thelapisfox** [comment]
You should probably delete this repository if you aren't going to update it. Didn't realize how old this program was thanks to google search results. Just so you know, attempting to unpack the current templates results in this error:

```
Starting bg-sedit!

Listing all blocks used in area.json to area-swap-map.json


Traceback (most recent call last):
  File "E:\New Backups\Downloads\bg-sedit-release-v1.0.0\sedit.py", line 137, in <module>
    unpack(args.schematic, args.map)
  File "E:\New Backups\Downloads\bg-sedit-release-v1.0.0\sedit.py", line 23, in unpack
    item_list = json_schematic["header"]["material_list"]["root_entry"]
                ~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'header'
```

[area.json](https://github.com/user-attachments/files/21449318/area.json)

And the current schematic
